Repository JanssenProject/jans, pull requests merged in 2021-12, with the labels that each got.

#107 chore: release jans-pycloudlib 1.0.0-beta.13
  CHANGELOG.md
Labels: autorelease: pending

#108 chore: release jans-pycloudlib 1.0.0-beta.13
  jans-pycloudlib/CHANGELOG.md
Labels: autorelease: pending

#112 chore(Dockerfile): updated build date
  docker-jans-auth-server/requirements.txt
  docker-jans-certmanager/requirements.txt
  docker-jans-client-api/requirements.txt
  docker-jans-config-api/requirements.txt
  docker-jans-configurator/requirements.txt
  docker-jans-fido2/requirements.txt
  docker-jans-persistence-loader/requirements.txt
  docker-jans-scim/requirements.txt
Labels: enhancement, bot

#106 chore: release docker-jans-persistence-loader 1.0.0-beta.13
  docker-jans-persistence-loader/CHANGELOG.md
  docker-jans-persistence-loader/version.txt
Labels: autorelease: pending

#113 chore: release docker-jans-persistence-loader 1.0.0-beta.13
  docker-jans-persistence-loader/CHANGELOG.md
Labels: autorelease: pending

#105 chore: release docker-jans-scim 1.0.0-beta.13
  docker-jans-scim/CHANGELOG.md
  docker-jans-scim/version.txt
Labels: autorelease: pending

#104 chore: release docker-jans-auth-server 1.0.0-beta.13
  docker-jans-auth-server/CHANGELOG.md
  docker-jans-auth-server/version.txt
Labels: autorelease: pending

#103 chore: release docker-jans-fido2 1.0.0-beta.13
  docker-jans-fido2/CHANGELOG.md
  docker-jans-fido2/version.txt
Labels: autorelease: pending

#102 chore: release docker-jans-client-api 1.0.0-beta.13
  docker-jans-client-api/CHANGELOG.md
  docker-jans-client-api/version.txt
Labels: autorelease: pending

#101 chore: release docker-jans-certmanager 1.0.0-beta.13
  docker-jans-certmanager/CHANGELOG.md
  docker-jans-certmanager/version.txt
Labels: autorelease: pending

#100 chore: release docker-jans-config-api 1.0.0-beta.13
  docker-jans-config-api/CHANGELOG.md
  docker-jans-config-api/version.txt
Labels: autorelease: pending

#99 chore: release docker-jans-configurator 1.0.0-beta.13
  docker-jans-configurator/CHANGELOG.md
  docker-jans-configurator/version.txt
Labels: autorelease: pending

#158 chore(Dockerfiles): updated janspycloud build in cn-secure-passwd
  docker-jans-auth-server/requirements.txt
  docker-jans-certmanager/requirements.txt
  docker-jans-client-api/requirements.txt
  docker-jans-config-api/requirements.txt
  docker-jans-configurator/requirements.txt
  docker-jans-fido2/requirements.txt
  docker-jans-persistence-loader/requirements.txt
  docker-jans-scim/requirements.txt
Labels: enhancement, bot

#160 fix(certmanager): handle issues reported by CodeQL
  docker-jans-certmanager/scripts/bootstrap.py
  docker-jans-certmanager/scripts/client_api_handler.py
  docker-jans-certmanager/scripts/utils.py
Labels: bug, enhancement, docker-cert-manager

#159 fix: always close file descriptors after parsing LDIF files
  docker-jans-persistence-loader/scripts/couchbase_setup.py
  docker-jans-persistence-loader/scripts/ldap_setup.py
Labels: bug, 1.0, docker-jans-persistence-loader

#163 chore(Dockerfiles): updated janspycloud build in cn-secure-passwd
  docker-jans-auth-server/requirements.txt
  docker-jans-certmanager/requirements.txt
  docker-jans-client-api/requirements.txt
  docker-jans-config-api/requirements.txt
  docker-jans-configurator/requirements.txt
  docker-jans-fido2/requirements.txt
  docker-jans-persistence-loader/requirements.txt
  docker-jans-scim/requirements.txt
Labels: enhancement, bot

#152 feat: deprecate password files in favor of secrets
  .github/CODEOWNERS
  .github/workflows/central_code_quality_check.yml
  .github/workflows/commit-check.yml
  .github/workflows/docker_build_image.yml
  .github/workflows/docker_imagescan.yml
  .github/workflows/jans_pycloud_build_package.yml
  docker-jans-auth-server/Dockerfile
  docker-jans-auth-server/requirements.txt
  docker-jans-certmanager/Dockerfile
  docker-jans-certmanager/requirements.txt
  docker-jans-client-api/Dockerfile
  docker-jans-client-api/requirements.txt
  docker-jans-config-api/Dockerfile
  docker-jans-config-api/requirements.txt
  docker-jans-configurator/Dockerfile
  docker-jans-configurator/README.md
  docker-jans-configurator/requirements.txt
  docker-jans-configurator/scripts/bootstrap.py
  docker-jans-configurator/scripts/parameter.py
  docker-jans-fido2/Dockerfile
  docker-jans-fido2/requirements.txt
  docker-jans-persistence-loader/requirements.txt
  docker-jans-scim/Dockerfile
  docker-jans-scim/requirements.txt
  jans-pycloudlib/jans/pycloudlib/persistence/couchbase.py
  jans-pycloudlib/jans/pycloudlib/persistence/sql.py
  jans-pycloudlib/jans/pycloudlib/utils.py
  jans-pycloudlib/tests/conftest.py
  jans-pycloudlib/tests/test_persistence.py
  jans-pycloudlib/tests/test_utils.py
Labels: docker-certmanager, docker-jans-persistence-loader, docker-jans-auth-server, docker-jans-client-api, docker-jans-config-api, docker-jans-configurator, docker-jans-fido2, docker-jans-scim, jans-pycloudlib

#165 chore(Dockerfiles): updated janspycloud build
  docker-jans-auth-server/requirements.txt
  docker-jans-certmanager/requirements.txt
  docker-jans-client-api/requirements.txt
  docker-jans-config-api/requirements.txt
  docker-jans-configurator/requirements.txt
  docker-jans-fido2/requirements.txt
  docker-jans-persistence-loader/requirements.txt
  docker-jans-scim/requirements.txt
Labels: enhancement, bot

#149 chore: release docker-jans-persistence-loader 1.0.0-beta.14
  docker-jans-persistence-loader/CHANGELOG.md
Labels: autorelease: pending

#141 chore: release jans-pycloudlib 1.0.0-beta.14
  jans-pycloudlib/CHANGELOG.md
Labels: autorelease: pending

#144 chore: release docker-jans-configurator 1.0.0-beta.14
  docker-jans-configurator/CHANGELOG.md
Labels: autorelease: pending

#167 chore: release docker-jans-persistence-loader 1.0.0-beta.14
  docker-jans-persistence-loader/CHANGELOG.md
Labels: autorelease: pending

#148 chore: release docker-jans-fido2 1.0.0-beta.14
  docker-jans-fido2/CHANGELOG.md
Labels: autorelease: pending

#147 chore: release docker-jans-config-api 1.0.0-beta.14
  docker-jans-config-api/CHANGELOG.md
Labels: autorelease: pending

#146 chore: release docker-jans-auth-server 1.0.0-beta.14
  docker-jans-auth-server/CHANGELOG.md
Labels: autorelease: pending

#145 chore: release docker-jans-scim 1.0.0-beta.14
  docker-jans-scim/CHANGELOG.md
Labels: autorelease: pending

#143 chore: release docker-jans-client-api 1.0.0-beta.14
  docker-jans-client-api/CHANGELOG.md
Labels: autorelease: pending

#142 chore: release docker-jans-certmanager 1.0.0-beta.14
  docker-jans-certmanager/CHANGELOG.md
Labels: autorelease: pending
